# WardenEssentials Config
# Use wisely

messages:
  join-welcome: "&aWelcome back to server!"
  join-help: "&eUse '/wessentials help' to see cmds."
  ban-message: "&cYou are banned from this server! Reason: %reason%"
  kick-message: "&cYou have been kicked! Reason: %reason%"
  broadcast-ban: "&c%player% was banned. Reason: %reason%"
  broadcast-kick: "&c%player% was kicked. Reason: %reason%"
  broadcast-unban: "&a%player% was unbanned by %sender%"
  vanish-on: "&aYou have vanished!"
  vanish-off: "&cYou are now visible!"
  vanish-broadcast-on: "&e%player% has vanished."
  vanish-broadcast-off: "&e%player% is visible again."
  vanish-hide-joinquit: true #True by default
  banip-broadcast: "&cIP %ip% has been banned by %player%!"
  unbanip-broadcast: "&eIP %ip% has been unbanned by %player%."
  banip-reason-default: "&cBanned by an operator."

# BOSSBAR CONFIGURATION
bossbar:
  # Bossbar should be enabled?
  enabled: false
  # What title should be on bossbar?
  title: "&bWelcome to the Warden Server!"
  # What color will be the bossbar?
  color: "PURPLE"
  # How should progress bar will be filled? default is 1.0.
  progress: 1.0
