name: WardenEssentials
version: 1.1.1
main: com.svhteam.lifesteal.wardenEssentials.WardenEssentials
api-version: 1.21
authors: [ NoFailsXD ]
commands:
  wessentials:
    description: WardenEssentials main command
    usage: /wessentials help
  weban:
    description: Ban a player with a reason
    usage: /weban <player> <reason>
    permission: wardenessentials.ban
  weunban:
    description: Unban a player
    usage: /weunban <player>
    permission: wardenessentials.unban
  givewardenblade:
    description: Gives the player the Warden Blade
    usage: /givewardenblade
    permission: wardenessentials.blade
  wekill:
    description: Kill a player
    usage: /wekill <player>
    permission: wardenessentials.kill
  wegive:
    description: Give an item to a player
    usage: /wegive <player> <item> [amount]
    permission: wardenessentials.give
permissions:
  wardenessentials.ban:
    description: Allows banning players
    default: op
  wardenessentials.unban:
    description: Allows unbanning players
    default: op
  wardenessentials.blade:
    description: Allows player to get the Warden Blade
    default: op
  wardenessentials.kill:
    description: Allow killing players
    default: op
  wardenessentials.give:
    description: Allow giving items
    default: op
