name: WardenEssentials
version: 1.1.6
main: com.svhteam.lifesteal.wardenEssentials.WardenEssentials
api-version: 1.21
authors: [ NoFailsXD ]
commands:
  wessentials:
    description: WardenEssentials main command
    usage: /wessentials help
  weban:
    description: Ban a player with a reason
    usage: /weban <player> <reason>
    permission: wardenessentials.ban
  weunban:
    description: Unban a player
    usage: /weunban <player>
    permission: wardenessentials.unban
  givewardenblade:
    description: Gives the player the Warden Blade
    usage: /givewardenblade
    permission: wardenessentials.blade
  wekill:
    description: Kill a player
    usage: /wekill <player>
    permission: wardenessentials.kill
  wegive:
    description: Give an item to a player
    usage: /wegive <player> <item> [amount]
    permission: wardenessentials.give
  weup:
    description: Place a block under you and go up.
    usage: /weup [height]
    permission: wardenessentials.up
  weeffect:
    description: Gives a player a potion effect
    usage: /weeffect <player> <effect> <duration_seconds> <amplifier>
    permission: wardenessentials.effect
  hidemynametag:
    description: Toggle your nametag visibility.
    usage: /<command>
    permission: wardenessentials.hidemynametag
  hideleaveandjoin:
    description: Toggle join/leave messages globally.
    usage: /<command>
    permission: wardenessentials.hideleave
  westop:
    description: Stops the server
    usage: /westop
    permission: wardenessentials.stop
  weinvsee:
    description: View another player's inventory
    usage: /weinvsee <player>
    permission: wardenessentials.invsee
  wesmite:
    description: Strike a player with lighting
    usage: /wesmite <player>
    permission: wardenessentials.smite
  weheal:
    description: Fully heal yourself or another player
    usage: /weheal [player]
    permission: wardenessentials.heal
  wefly:
    description: Toggle flight for yourself or another player
    usage: /wefly [player]
    permission: wardenessentials.fly
  wetp:
    description: Teleport to a player
    usage: /wetp <player>
    permission: wardenessentials.tp
  wetphere:
    description: Teleport a player to you
    usage: /wetphere <player>
    permission: wardenessentials.tphere
  wetime:
    description: Changes the time of day
    usage: /wetime <day|night|noon|midnight>
    permission: wardenessentials.time
  weweather:
      description: Changes the weather
      usage: /weweather <clear|rain|storm>
      permission: wardenessentials.weather
  wealert:
    description: Sends a server-wide alert
    usage: /wealert <message>
    permission: wardenessentials.alert
  wefind:
      description: Finds a player's coordinates
      usage: /wefind <player>
      permission: wardenessentials.find
  wefeed:
    description: Feed yourself
    usage: /wefeed
    permission: wardenessentials.feed
  wehome:
      description: Teleport to your home
      usage: /wehome
      permission: wardenessentials.home
  wesethome:
      description: Set your home
      usage: /wesethome
      permission: wardenessentials.sethome
  wegm:
      description: Change gamemode
      usage: /wegm <mode> [player]
      permission: wardenessentials.gamemode
permissions:
  wardenessentials.ban:
    description: Allows banning players
    default: op
  wardenessentials.unban:
    description: Allows unbanning players
    default: op
  wardenessentials.blade:
    description: Allows player to get the Warden Blade
    default: op
  wardenessentials.kill:
    description: Allow killing players
    default: op
  wardenessentials.give:
    description: Allow giving items
    default: op
  wardenessentials.up:
    description: Allow use of /weup
    default: op
  wardenessentials.effect:
    description: Allow giving potion effects
    default: op
  wardenessentials.stop:
    description: Allows stopping the server
    default: op
  wardenessentials.invsee:
    description: Allow viewing another player's inventory
    default: op
  wardenessentials.smite:
    description: Allows striking a player with lighting
    default: op
  wardenessentials.heal:
    description: Allows healing yourself or others
    default: op
  wardenessentials.fly:
    description: Allows toggling flight
    default: op
  wardenessentials.tp:
    description: Allows teleporting to another player
    default: op
  wardenessentials.tphere:
    description: Allows teleporting another player to you
    default: op
  wardenessentials.time:
    description: Allows changing the time of day
    default: op
  wardenessentials.weather:
      description: Allows changing the weather
      default: op
  wardenessentials.alert:
    description: Allows sending alerts
    default: op
  wardenessentials.find:
      description: Allows finding player coordinates
      default: op
  wardenessentials.hidemynametag:
    description: Allows hiding your nametag
    default: op

  wardenessentials.hideleave:
    description: Allows toggling join/leave messages globally
    default: op
  wardenessentials.feed:
    description: Allows player to use /wefeed
    default: op
  wardenessentials.home:
      description: Allows player to use /wehome
      default: true
  wardenessentials.sethome:
      description: Allows player to use /wesethome
      default: true
  wardenessentials.gamemode:
      description: Allows player to change gamemode
      default: op
